service: payment-lambda

provider:
  name: aws
  runtime: nodejs12.x
  stage: live
  region: ap-northeast-1
  environment:
    LIVE_STRIPE_SECRET_KEY: ${env:LIVE_STRIPE_SECRET_KEY}

functions:
  checkout:
    handler: checkout.handler
    events:
      - http:
          path: checkout
          method: POST
          cors: true
