service: payment-lambda

provider:
  name: aws
  runtime: nodejs12.x
  stage: test
  region: ap-northeast-1
  environment:
    TEST_STRIPE_SECRET_KEY:
    LIVE_STRIPE_SECRET_KEY:

functions:
  checkout:
    handler: checkout.handler
    events:
      - http:
          path: checkout
          method: POST
          cors: true
